---
name: get_config
pack: sim_fsaas
runner_type: "python-script"
description: Generate Response
enabled: true
entry_point: fsaas_get_config.py
parameters:
  cluster:
    type: string
    description: Cluster Name
    required: true
  
      