pack: melair_core
enabled: true
runner_type: orquesta
name: prod_onboard_privileged_user
entry_point: workflows/prod_onboard_privileged_user.yaml
parameters:
  data:
    type: object
    description: input json payload