---
ssl_verify:
  description: "Verify SSL certificate used with backup Server."
  type: boolean
  default: True

braas:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/backup"
  additionalProperties: false

backup:
  type: "object"
  properties:
    host:
      description: "Hostname or IP address of backup Server."
      type: "string"
      required: true
    user:
      description: "Authentication user-id for the backup Server."
      type: "string"
      required: true
    passwd:
      description: "The password of the specified user."
      type: "string"
      secret: true
      required: true
  additionalProperties: false
