---
version: 1.0

description: Sample orquesta automation 

#input variables 
input:
  - data

#tasks 
tasks:
  execute:
    action: sim_vmwaree.greet 
    input:
      greeting: "hello"
    next:
      - when: <% succeeded() %>
        publish:
          - state: FINISHED
          - info: <% result().stdout  %>

output:
  - state: <% ctx().state %>
  - info:  <% ctx().info %>
