version: 1.0
tasks:
  # [59, 21]
  start:
    action: core.noop
    next:
      - do:
          - update_itsm
        publish:
          - first_sim_update: Automation has started the execution of request for ITSM ticket number - <% ctx().ticket_id%>
          - close_date: "<% now().format(\"%Y-%m-%d %H:%M:%S\") %>"
  # [57, 234]
  password_from_pwdstate:
    action: sim_passwordstate.get_details_from_password_id
    input:
      log_level: DEBUG
      api_key: b75264dfca3983e52d4cab368e93f768
      password_id: 27535
    next:
      - do:
          - create_invite_external_user
        publish:
          - client_id: <% result().result.json_response[0].UserName %>
          - client_secret: <% result().result.json_response[0].Password%>
  # [59, 342]
  create_invite_external_user:
    action: sim_core.create_and_invite_external_user
    input:
      log_level: DEBUG
      external_user_email: <%ctx().external_user_email%>
      sponsor_email: <%ctx().sponsor%>
      client_id: <%ctx().client_id%>
      client_secret: <%ctx().client_secret%>
      company: <%ctx().company%>
      given_name: <%ctx().given_name%>
      surname: <%ctx().surname%>
      tenant_id: b02e50ac-20e5-4c60-bcd4-8454b3201fd1
    next:
      - do:
          - update_external_user_details
        publish:
          - object_id: <% result().result.invitedUser.id %>
          - display_name: <% result().result.invitedUserDisplayName %>
          - invitedUserType: <% result().result.invitedUserType %>
          - invitedUserEmailAddress: <% result().result.invitedUserEmailAddress%>
          - sendInvitationMessage: <% result().result.sendInvitationMessage%>
          - inviteRedirectUrl: <% result().result.inviteRedirectUrl%>
  # [327, 160]
  update_external_user_details:
    action: sim_core.update_external_user_attributes
    input:
      log_level: DEBUG
      sponsor: <%ctx().sponsor%>
      client_secret: <%ctx().client_secret%>
      client_id: <%ctx().client_id%>
      company: <%ctx().company%>
      given_name: <%ctx().given_name%>
      surname: <%ctx().surname%>
      tenant_id: b02e50ac-20e5-4c60-bcd4-8454b3201fd1
      ticket: <%ctx().ticket_id%>
      user_object_id: <%ctx().object_id%>
    next:
      - do:
          - update_extension_external_user
  # [691, 84]
  update_extension_external_user:
    action: sim_core.update_extension_external_user
    input:
      log_level: DEBUG
      client_id: <%ctx().client_id%>
      client_secret: <%ctx().client_secret%>
      ext15: extension_22a751116fa241d98073c47baeb4b562_msDS_cloudExtensionAttribute15
      ext16: extension_22a751116fa241d98073c47baeb4b562_msDS_cloudExtensionAttribute16
      object_id: <%ctx().object_id%>
      tenant_id: b02e50ac-20e5-4c60-bcd4-8454b3201fd1
      ticket: <%ctx().ticket_id%>
      sponsor: <%ctx().sponsor%>
      notes: demo test on <%ctx().ticket_id%>
    next:
      - do:
          - send_email_sponsor
        publish:
          - end_date: <% result().result.end_date %>
  # [693, 199]
  send_email_sponsor:
    action: core.sendmail
    input:
      from: SiM.Automation@ethan.com.au
      to: <%ctx().sponsor%>
      subject: New external user <%ctx().display_name%>
      body: "<div>New external user <%ctx().display_name%> (<%ctx().sponsor%>) has been created in Ethan.</div>\n<div></div>\n<div>Please review this page for information: https://ecorpsystems.sharepoint.com/:w:/s/ogrp-ethan-ecorpbuild/ESxBexJO3C9CugLa3_IPQPwBUrf9vJws0NgMQbuTsK23og?e=AnnW2l</div>\n<div></div>\n<div>If further assistance is required, please create a helpdesk ticket on behalf of the external user. Ensure that you include their contact details.</div>\n<div></div>\n<div>Note that the account will be automatically disabled in 6 months  on  <%ctx().end_date%></div>"
    next:
      - do:
          - resolve_ticket
  # [698, 484]
  end:
    action: core.noop
  # [58, 132]
  update_itsm:
    action: sim_itsm2.update
    input:
      log_level: DEBUG
      number: <%ctx().ticket_id%>
      payload:
        comments: <% ctx().first_sim_update %>
        state: 10
        assigned_to: svc_sim_automation
        service_offering: SDaaS
      table: sn_customerservice_general_case
    next:
      - do:
          - password_from_pwdstate
  # [699, 371]
  resolve_ticket:
    action: sim_itsm2.update
    next:
      - do:
          - end
    input:
      log_level: DEBUG
      number: <% ctx().ticket_id %>
      payload:
        comments: Sim Automation is resolving the service request after successfully creating the Guest User,  inviting the Guest User & notifying Sponsor.
        resolution_code: Completed
        close_notes: Sim Automation is resolving the service request after completion of operation as per request
        state: 3
        cause: User Termination request completed by SiM Automation
        assigned_to: svc_sim_automation
        closed_by: 84cf417087ff3410bd1d32e80cbb3502
        closed_at: <% ctx().close_date %>
        notes_to_comments: true
      table: sn_customerservice_general_case
input:
  - external_user_email
  - sponsor
  - given_name
  - surname
  - company
  - ticket_id
