version: 1.0
tasks:
  # [36, 42]
  start:
    action: core.noop
    next:
      - do:
          - webex_update
        publish:
          - first_sim_update: Automation has started the execution of request for ITSM ticket number - <% ctx().ticket_id%>
          - close_date: "<% now().format(\"%Y-%m-%d %H:%M:%S\") %>"
  # [38, 361]
  password_from_pwdstate:
    action: sim_passwordstate.get_details_from_password_id
    input:
      log_level: DEBUG
      api_key: 578abdf3e64c392e4cb8d3f65a7923d6
      password_id: 30399
    next:
      - do:
          - access_token
        publish:
          - client_id: <% result().result.json_response[0].UserName %>
          - client_secret: <% result().result.json_response[0].Password%>
  # [39, 581]
  create_invite_external_user:
    action: sim_core.create_and_invite_external_user
    input:
      log_level: DEBUG
      external_user_email: <%ctx().external_user_email%>
      sponsor_email: <%ctx().sponsor%>
      company: <%ctx().company%>
      given_name: <%ctx().given_name%>
      surname: <%ctx().surname%>
      access_token: <%ctx().access_token%>
    next:
      - do:
          - update_external_user_details
        publish:
          - object_id: <% result().result.invitedUser.id %>
          - display_name: <% result().result.invitedUserDisplayName %>
          - invitedUserType: <% result().result.invitedUserType %>
          - invitedUserEmailAddress: <% result().result.invitedUserEmailAddress%>
          - sendInvitationMessage: <% result().result.sendInvitationMessage%>
          - inviteRedirectUrl: <% result().result.inviteRedirectUrl%>
  # [399, 145]
  update_external_user_details:
    action: sim_core.update_external_user_attributes
    input:
      log_level: DEBUG
      sponsor: <%ctx().sponsor%>
      company: <%ctx().company%>
      given_name: <%ctx().given_name%>
      surname: <%ctx().surname%>
      ticket: <%ctx().ticket_id%>
      user_object_id: <%ctx().object_id%>
      access_token: <%ctx().access_token%>
    next:
      - do:
          - update_extension_external_user
  # [706, 144]
  update_extension_external_user:
    action: sim_core.update_extension_external_user
    input:
      log_level: DEBUG
      ext15: extension_ee0e615249074199abbe00d591a8e582_msDS_cloudExtensionAttribute15
      ext16: extension_ee0e615249074199abbe00d591a8e582_msDS_cloudExtensionAttribute16
      object_id: <%ctx().object_id%>
      ticket: <%ctx().ticket_id%>
      sponsor: <%ctx().sponsor%>
      notes: Created with Ethan CSP Ticket <%ctx().ticket_id%>
      token: <%ctx().access_token%>
    next:
      - do:
          - update_result
        publish:
          - end_date: <% result().result.end_date %>
          - status: <% result().result.status %>
        when: i
  # [937, 388]
  send_email_sponsor:
    action: core.sendmail
    input:
      from: SiM.Automation@ethan.com.au
      to: <%ctx().sponsor%>
      subject: New external user <%ctx().display_name%>
      body: "<div>New external user <%ctx().display_name%> (<%ctx().sponsor%>) has been created in Ethan.</div>\n<div></div>\n<div>Please review this page for information: https://ecorpsystems.sharepoint.com/:w:/s/ogrp-ethan-ecorpbuild/ESxBexJO3C9CugLa3_IPQPwBUrf9vJws0NgMQbuTsK23og?e=AnnW2l</div>\n<div></div>\n<div>If further assistance is required, please create a helpdesk ticket on behalf of the external user. Ensure that you include their contact details.</div>\n<div></div>\n<div>Note that the account will be automatically disabled in 6 months  on  <%ctx().end_date%></div>"
    next:
      - do:
          - resolve_ticket
  # [940, 723]
  end:
    action: core.noop
  # [38, 250]
  update_itsm:
    action: sim_itsm2.update
    input:
      log_level: DEBUG
      number: <%ctx().ticket_id%>
      payload:
        comments: <% ctx().first_sim_update %>
        state: 10
        assigned_to: svc_sim_automation
        service_offering: SDaaS
      table: sn_customerservice_general_case
    next:
      - do:
          - password_from_pwdstate
  # [937, 496]
  resolve_ticket:
    action: sim_itsm2.update
    next:
      - do:
          - result_update_webex
    input:
      log_level: DEBUG
      number: <% ctx().ticket_id %>
      payload:
        comments: Sim Automation is resolving the service request after successfully creating the Guest User,  inviting the Guest User & notifying Sponsor.
        resolution_code: Completed
        close_notes: Sim Automation is resolving the service request after completion of operation as per request
        state: 3
        cause: User Termination request completed by SiM Automation
        assigned_to: svc_sim_automation
        closed_by: 84cf417087ff3410bd1d32e80cbb3502
        closed_at: <% ctx().close_date %>
        notes_to_comments: true
      table: sn_customerservice_general_case
  # [38, 473]
  access_token:
    action: sim_o365.get_graphapi_token
    next:
      - do:
          - create_invite_external_user
        publish:
          - access_token: <% result().output.graph_auth_token %>
    input:
      client_id: <%ctx().client_id%>
      client_secret: <%ctx().client_secret%>
      tenant_id: 455ac8b0-5713-4dd7-be28-3898e9505f7e
  # [37, 142]
  webex_update:
    action: cisco_webex.webex_post_message
    next:
      - do:
          - update_itsm
    input:
      log_level: DEBUG
      bearer_token: N2U5NzA4NmYtYjM3OC00MGRjLWE2NDItYWQwMmRjMWUwNWY0N2IzMWIxM2YtNWMx_PF84_17d3c97c-98f4-4894-9db9-e446ba46550e
      room_id: Y2lzY29zcGFyazovL3VzL1JPT00vMDQ1NjZjNjAtOGMwMi0xMWVlLWIwMGYtMjc5MGE1NGY0NzRl
      text: "Guest user automation workflow started , ticket no: <%ctx().ticket_id%>"
  # [939, 609]
  result_update_webex:
    action: cisco_webex.webex_post_message
    input:
      log_level: DEBUG
      bearer_token: N2U5NzA4NmYtYjM3OC00MGRjLWE2NDItYWQwMmRjMWUwNWY0N2IzMWIxM2YtNWMx_PF84_17d3c97c-98f4-4894-9db9-e446ba46550e
      room_id: Y2lzY29zcGFyazovL3VzL1JPT00vMDQ1NjZjNjAtOGMwMi0xMWVlLWIwMGYtMjc5MGE1NGY0NzRl
      text: "Guest user workflow run successfully , ticket no:<%ctx().ticket_id%>"
    next:
      - do:
          - end
  # [709, 269]
  update_result:
    action: core.noop
    next:
      - do:
          - send_email_sponsor
        when: <% ctx().status = "success" %>
      - do:
          - failed
        when: <% ctx().status != "success" %>
  # [576, 393]
  failed:
    action: core.noop
    next:
      - do:
          - fail_update_webex
  # [575, 507]
  fail_update_webex:
    action: cisco_webex.webex_post_message
    input:
      log_level: DEBUG
      bearer_token: N2U5NzA4NmYtYjM3OC00MGRjLWE2NDItYWQwMmRjMWUwNWY0N2IzMWIxM2YtNWMx_PF84_17d3c97c-98f4-4894-9db9-e446ba46550e
      room_id: Y2lzY29zcGFyazovL3VzL1JPT00vMDQ1NjZjNjAtOGMwMi0xMWVlLWIwMGYtMjc5MGE1NGY0NzRl
      text: "Guest User automation failed "
input:
  - external_user_email
  - sponsor
  - given_name
  - surname
  - company
  - ticket_id
