---
url: "https://netdb.essist.com.au/api/v1/cpe"
auth_token: "0ab414e6487e35477157f38640f58e8ae6a0df89"
compliance:
  - check_name: Enable aaa new model
    check_code: 1.1.1
    regex_to_match: (?<!\! )aaa new-model
    look_for_match_yes_no: yes
  - check_name: Enable aaa authentication login
    check_code: 1.1.2
    regex_to_match: (?<!\! )aaa authentication login
    look_for_match_yes_no: yes
  - check_name: Enable aaa authentication enable default
    check_code: 1.1.3
    regex_to_match: (?<!\! )aaa authentication enable default
    look_for_match_yes_no: yes
  - check_name: Set login authentication for line con 0
    check_code: 1.1.4
    regex_to_match: (?<!\! )login authentication for line con 0
    look_for_match_yes_no: yes
  - check_name: Set login authentication for line tty
    check_code: 1.1.5
    regex_to_match: (?<!\! )login authentication for line tty
    look_for_match_yes_no: yes
  - check_name: Set login authentication for line vty
    check_code: 1.1.6
    regex_to_match: (?<!\!)login authentication for line vty
    look_for_match_yes_no: yes
  - check_name: Disable ip http server
    check_code: 1.1.7
    regex_to_match: (?<!\! )no ip http server
    look_for_match_yes_no: yes
  - check_name: Disable ip http secure-server
    check_code: 1.1.8
    regex_to_match: (?<!\! )no ip http secure-server
    look_for_match_yes_no: yes
  - check_name: Privilege level check for Fallback user
    check_code: 1.2.1
    regex_to_match: (?<!\! )username (.+) privilege 15 secret
    look_for_match_yes_no: yes
    lookup_value_count: 1
  - check_name: Set transport input ssh for line vty connections
    check_code: 1.2.2
    regex_to_match: (?<!\! )line vty[\s\S]+?transport input ssh
    look_for_match_yes_no: yes
  - check_name: Set no exec for line aux
    check_code: 1.2.3
    regex_to_match: (?<!\! )line aux[\s\S]?[\s\S]+?(?<=no-exec)[\s\S]+?line(.+)$
    look_for_match_yes_no: yes
  - check_name: Set access-class for use with line vty connections
    check_code: 1.2.5
    regex_to_match: (?<!\! )line vty[\s\S]?[\s\S]+?(?<=access-class)[\s\S]+?line(.+)$
    look_for_match_yes_no: yes
  - check_name: Create access-list for use with line vty connections
    check_code: 1.2.4
    regex_to_match: (?<!\! )
    look_for_match_yes_no: yes
  - check_name: Set exec-timeout to less than or equal to 10 minutes line console 0
    check_code: 1.2.7
    regex_to_match: (?<!\! )line con[\s\S]?[\s\S]+?(?<=exec-timeout)[\s\S]+?line(.+)$
    look_for_match_yes_no: yes
  - check_name: Set exec-timeout to less than or equal to 10 minutes line tty 0
    check_code: 1.2.8
    regex_to_match: (?<!\! )line vty[\s\S]?[\s\S]+?(?<=exec-timeout)[\s\S]+?line(.+)$
    look_for_match_yes_no: yes
  - check_name: Set exec-timeout to less than or equal to 10 minutes line vty 0
    check_code: 1.2.9
    regex_to_match: (?<!\! )line vty[\s\S]?[\s\S]+?(?<=exec-timeout)[\s\S]+?line(.+)$
    look_for_match_yes_no: yes
  - check_name: Set exec-timeout to less than or equal to 10 minutes line aux 0
    check_code: 1.2.6
    regex_to_match: (?<!\! )line aux[\s\S]?[\s\S]+?(?<=exec-timeout)[\s\S]+?line(.+)$
    look_for_match_yes_no: yes
  - check_name: Set transport input none for line aux
    check_code: 1.2.10
    regex_to_match: (?<!\! )line aux[\s\S]?[\s\S]+?(?<=transport input none)[\s\S]+?line(.+)$
    look_for_match_yes_no: yes
  - check_name: Set the banner-text for banner exec
    check_code: 1.3.1
    regex_to_match: (?<!\! )banner exec
    look_for_match_yes_no: yes
  - check_name: Set the banner-text for banner login
    check_code: 1.3.2
    regex_to_match: (?<!\! )banner login
    look_for_match_yes_no: yes
  - check_name: Set the banner-text for banner motd
    check_code: 1.3.4
    regex_to_match: (?<!\! )banner motd
    look_for_match_yes_no: yes
  - check_name: Set password for enable secret
    check_code: 1.4.1
    regex_to_match: (?<!\! )enable secret
    look_for_match_yes_no: yes
  - check_name: Enable password service-encryption
    check_code: 1.4.2
    regex_to_match: (?<!\! )password service-encryption
    look_for_match_yes_no: yes
  - check_name: Enable username secret for all local users
    check_code: 1.4.3
    regex_to_match: (?<!\! )username .+ privilege 15 (.+)
    look_for_match_yes_no: yes
    lookup_value: secret
  - check_name: Set the hostname
    check_code: 2.1.1.1.1
    regex_to_match: (?<!\! )hostname (.+)
    look_for_match_yes_no: yes
  - check_name: Set the ip domain-name
    check_code: 2.1.1.1.2
    regex_to_match: (?<!\! )ip domain name (.+)
    look_for_match_yes_no: yes
  - check_name: Running the secure version of SSH
    check_code: 2.1.1.2
    regex_to_match: (?<!\! )ip ssh version 2
    look_for_match_yes_no: yes
  - check_name: SSH Timeout
    check_code: 2.1.1.1.4
    regex_to_match: (?<!\! )ip ssh timeout
    look_for_match_yes_no: yes
  - check_name: SSH Authentication Retries
    check_code: 2.1.1.1.5
    regex_to_match: (?<!\! )ip ssh authentication-retries
    look_for_match_yes_no: yes
  - check_name: Enable system message logging to a local buffe
    check_code: 2.2.2
    regex_to_match: (?<!\! )logging buffered
    look_for_match_yes_no: yes
  - check_name: Logging critical logs to device console
    check_code: 2.2.3
    regex_to_match: (?<!\! )logging console critical
    look_for_match_yes_no: yes
  - check_name: Log system messages and debug output to a remote host
    check_code: 2.2.4
    regex_to_match: (?<!\! )logging host (.+)
    look_for_match_yes_no: yes
  - check_name: Limit messages logged to the syslog servers based on severity level informational
    check_code: 2.2.5
    regex_to_match: (?<!\! )logging trap informational
    look_for_match_yes_no: yes
  - check_name: Apply a time stamp to debugging messages or system logging messages
    check_code: 2.2.6
    regex_to_match: (?<!\! )service timestamps debug datetime msec
    look_for_match_yes_no: yes
  - check_name: Bind logging to Loopback Interface
    check_code: 2.2.7
    regex_to_match: (?<!\! )logging source-interface Loopback\d+
    look_for_match_yes_no: yes
  - check_name: Audit Loggin for Login Failures and Success
    check_code: 2.2.8
    regex_to_match: (?<!\! )login on-success log[\s\S]+(?:(?<!\!)login on-failure log)
    look_for_match_yes_no: yes
  - check_name: Set an IP for the NTP server
    check_code: 2.3.2
    regex_to_match: (?<!\! )ntp server
    look_for_match_yes_no: yes
  - check_name: Single Loopback Interface Check
    check_code: 2.4.1
    regex_to_match: (?<!\! )interface Loopback
    look_for_match_yes_no: yes
    lookup_value_count: 1
  - check_name: Force AAA to use the IP address of a specified interface for all outgoing AAA packets
    check_code: 2.4.2
    regex_to_match: (?<!\! )ip radius source-interface
    look_for_match_yes_no: yes
  - check_name: Bind the NTP service to the loopback interface.
    check_code: 2.4.3
    regex_to_match: (?<!\! )ntp server (.+) ? source Loopback
    look_for_match_yes_no: yes
  - check_name: Bind the TFTP client to the loopback interface
    check_code: 2.4.4
    regex_to_match: (?<!\! )ip tftp source-interface Loopback
    look_for_match_yes_no: yes

