api_key: MTUzNGQzZmYwYmU5ZTM0YWJlZTQzNjhkOWM0MjVhYzI1OWRkMDQ2ZjkyZmFkOWYzMDNiYmZlZGFiNDZmNGQ3OQ
api_url: http://sim-central.sim.esecure.systems/api/v1
azure_blob_sas: sp=racwdli&st=2024-01-11T02:35:41Z&se=2025-01-11T10:35:41Z&spr=https&sv=2022-11-02&sr=c&sig=JCEAwxIa5vKiLCSLpyGDwXBty0B9TSGG6pcTk2e022I%3D
